sudo: false
osx_image: xcode8.3
language: objective-c
cache: bundler

install: 
- bundle install --without=documentation --path ../travis_bundle_dir
- export PATH=`python -m site --user-base`/bin:$PATH

script:
- make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -t de4c0f22-50e8-4168-a938-7ad99c468dce